project:
  type: website
  output-dir: docs

website:
  title: "dsci542-blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts
        text: Posts
